name: Sync Logs
on:
  schedule:
    - cron: '59 00 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Aspirer les fichiers (sauf index.html)
        run: |
          wget -r -np -nH --cut-dirs=3 -R "index.html" -A "*.html" http://83.228.222.219/root/xylem_data/public_html/ -P buhs/xylem/log/

      - name: Pousser les modifications
        run: |
          git config user.name "BigTree-Bot"
          git config user.email "bot@bigtree.com"
          git add .
          git commit -m "Mise à jour automatique des logs" || echo "Rien à mettre à jour"
          git push
